### ISSUE TITLE
Axis options not supported

### ISSUE THREAD

**Issue by talbrown** [lgaticaq/c3-exporter#1]
When using the axis option, the rendered image is empty. This is especially important for timeseries graphs.

The following options will incorrectly create an empty image:
{
    data:{
      columns: [
        ['x', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06','2013-01-07', '2013-01-08', '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12','2013-01-13', '2013-01-14',],
        ['y', 30, 200, 180, 380, 240, 330,400, 290,450, 620, 640, 530, 640, 580]
      ],
      colors:{
        data2: '#1ab394',
        y: '#1ab394 '
      },
      type: 'line',
      names: {y:'Risk Score'}
    },
    axis: {
      x: {
        type: 'timeseries',
        tick: {
          format: '%Y-%m-%d'
        }
      }
    }
  };

**Comment by lgaticaq** [comment]
You not declaring the x-axis
```javascript
const options = {
  data: {
    x: 'x', // THIS
    columns: [
      ['x', '2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08', '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12', '2013-01-13', '2013-01-14'],
      ['y', 30, 200, 180, 380, 240, 330, 400, 290, 450, 620, 640, 530, 640, 580]
    ],
    colors: {data2: '#1ab394', y: '#1ab394'},
    type: 'line',
    names: {y: 'Risk Score'}
  },
  axis: {
    x: {type: 'timeseries', tick: {format: '%Y-%m-%d'}}
  }
}
c3Exporter(options)
```
![chart-3763456238](https://cloud.githubusercontent.com/assets/661958/25537432/f066c8fc-2c2d-11e7-8a4e-5bbf5c36667d.png)
