### ISSUE TITLE
dependency errors

### ISSUE THREAD

**Issue by waqar-imtiaz** [lgaticaq/c3-exporter#14]
I am trying to get it in my angular app but I am getting the following dependency  errors:
"ERROR in ./node_modules/c3-exporter/index.js
Module not found: Error: Can't resolve 'child_process' in 'ui\node_modules\c3-exporter'"

how can i resolve this?

**Comment by lgaticaq** [comment]
Sorry. This lib is for Server Side (Node.js) only
